//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Ermoshin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EtoKonechErmoshinEntities : DbContext
    {
        public EtoKonechErmoshinEntities()
            : base("name=EtoKonechErmoshinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Rabotniki> Rabotniki { get; set; }
        public virtual DbSet<Rashodniki> Rashodniki { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipDeatelnosti> TipDeatelnosti { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserZayavka> UserZayavka { get; set; }
        public virtual DbSet<Zakazkhik> Zakazkhik { get; set; }
        public virtual DbSet<ZaplanirovannieUborka> ZaplanirovannieUborka { get; set; }
        public virtual DbSet<Zayavka> Zayavka { get; set; }
        public virtual DbSet<ZayavkaRabotniki> ZayavkaRabotniki { get; set; }
        public virtual DbSet<ZayavkaRashodniki> ZayavkaRashodniki { get; set; }
    }
}
