//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Ermoshin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rabotniki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rabotniki()
        {
            this.ZayavkaRabotniki = new HashSet<ZayavkaRabotniki>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public int TipDeatelnostiId { get; set; }
    
        public virtual TipDeatelnosti TipDeatelnosti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZayavkaRabotniki> ZayavkaRabotniki { get; set; }
    }
}
