//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Ermoshin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rashodniki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rashodniki()
        {
            this.ZayavkaRashodniki = new HashSet<ZayavkaRashodniki>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Kolichestvo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZayavkaRashodniki> ZayavkaRashodniki { get; set; }
    }
}
