//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Ermoshin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserZayavka
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ZayavkaId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Zayavka Zayavka { get; set; }
    }
}
