//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Ermoshin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazkhik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakazkhik()
        {
            this.Zayavka = new HashSet<Zayavka>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Organizatia { get; set; }
        public string Adres { get; set; }
        public Nullable<int> KolichestvoKomnat { get; set; }
        public int Ploshad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zayavka> Zayavka { get; set; }
    }
}
