//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Ermoshin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZayavkaRabotniki
    {
        public int id { get; set; }
        public int Zayavka { get; set; }
        public int Rabotniki { get; set; }
    
        public virtual Rabotniki Rabotniki1 { get; set; }
        public virtual Zayavka Zayavka1 { get; set; }
    }
}
